// GENERATED by scripts/optimize-images.py — do not edit by hand.
// Run `npm run images` after changing anything in _originals/.
/** @type {{ label: string, thumb: string, src: string }[]} */
export const gallery = [
	{
		label: "Conference photo 28",
		thumb: "/img/gallery-28-thumb.webp",
		src: "/img/gallery-28.webp"
	},
	{
		label: "Conference photo 43",
		thumb: "/img/gallery-43-thumb.webp",
		src: "/img/gallery-43.webp"
	},
	{
		label: "Conference photo 11",
		thumb: "/img/gallery-11-thumb.webp",
		src: "/img/gallery-11.webp"
	},
	{
		label: "Conference photo 40",
		thumb: "/img/gallery-40-thumb.webp",
		src: "/img/gallery-40.webp"
	},
	{
		label: "Nicole Johnston \u2014 When Being 'Too Much' Is Actually Just Enough",
		thumb: "/img/speaker-nicole-thumb.webp",
		src: "/img/speaker-nicole.webp"
	},
	{
		label: "The team after the show",
		thumb: "/img/stage-group-thumb.webp",
		src: "/img/stage-group.webp"
	},
	{
		label: "The Loeb Playhouse stage",
		thumb: "/img/student-speaker-hero-thumb.webp",
		src: "/img/student-speaker-hero.webp"
	},
	{
		label: "Conference photo 21",
		thumb: "/img/gallery-21-thumb.webp",
		src: "/img/gallery-21.webp"
	},
	{
		label: "Conference photo 08",
		thumb: "/img/gallery-08-thumb.webp",
		src: "/img/gallery-08.webp"
	},
	{
		label: "Jyotisman Rath, 2025 student speaker",
		thumb: "/img/winner-2025-b-thumb.webp",
		src: "/img/winner-2025-b.webp"
	},
	{
		label: "Conference photo 16",
		thumb: "/img/gallery-16-thumb.webp",
		src: "/img/gallery-16.webp"
	},
	{
		label: "Conference photo 38",
		thumb: "/img/gallery-38-thumb.webp",
		src: "/img/gallery-38.webp"
	},
	{
		label: "Conference photo 10",
		thumb: "/img/gallery-10-thumb.webp",
		src: "/img/gallery-10.webp"
	},
	{
		label: "The audience",
		thumb: "/img/audience-thumb.webp",
		src: "/img/audience.webp"
	},
	{
		label: "Conference photo 19",
		thumb: "/img/gallery-19-thumb.webp",
		src: "/img/gallery-19.webp"
	},
	{
		label: "Conference photo 29",
		thumb: "/img/gallery-29-thumb.webp",
		src: "/img/gallery-29.webp"
	},
	{
		label: "Bo Parfet \u2014 How Do You Light Your Soul on Fire?",
		thumb: "/img/speaker-bo-thumb.webp",
		src: "/img/speaker-bo.webp"
	},
	{
		label: "Conference photo 22",
		thumb: "/img/gallery-22-thumb.webp",
		src: "/img/gallery-22.webp"
	},
	{
		label: "Conference photo 31",
		thumb: "/img/gallery-31-thumb.webp",
		src: "/img/gallery-31.webp"
	},
	{
		label: "Conference photo 24",
		thumb: "/img/gallery-24-thumb.webp",
		src: "/img/gallery-24.webp"
	},
	{
		label: "Chase Boehringer \u2014 How to do impossible things",
		thumb: "/img/speaker-chase-thumb.webp",
		src: "/img/speaker-chase.webp"
	},
	{
		label: "The team on stage",
		thumb: "/img/conference-group-thumb.webp",
		src: "/img/conference-group.webp"
	},
	{
		label: "Aastha Patel, 2026 student speaker",
		thumb: "/img/winner-2026-thumb.webp",
		src: "/img/winner-2026.webp"
	},
	{
		label: "Conference photo 39",
		thumb: "/img/gallery-39-thumb.webp",
		src: "/img/gallery-39.webp"
	},
	{
		label: "Conference photo 17",
		thumb: "/img/gallery-17-thumb.webp",
		src: "/img/gallery-17.webp"
	},
	{
		label: "Conference photo 36",
		thumb: "/img/gallery-36-thumb.webp",
		src: "/img/gallery-36.webp"
	},
	{
		label: "Conference photo 33",
		thumb: "/img/gallery-33-thumb.webp",
		src: "/img/gallery-33.webp"
	},
	{
		label: "Conference photo 01",
		thumb: "/img/gallery-01-thumb.webp",
		src: "/img/gallery-01.webp"
	},
	{
		label: "Conference photo 12",
		thumb: "/img/gallery-12-thumb.webp",
		src: "/img/gallery-12.webp"
	},
	{
		label: "Conference photo 30",
		thumb: "/img/gallery-30-thumb.webp",
		src: "/img/gallery-30.webp"
	},
	{
		label: "Conference photo 18",
		thumb: "/img/gallery-18-thumb.webp",
		src: "/img/gallery-18.webp"
	},
	{
		label: "Prady Modukuru \u2014 From Building to Founding",
		thumb: "/img/speaker-prady-thumb.webp",
		src: "/img/speaker-prady.webp"
	},
	{
		label: "Conference photo 14",
		thumb: "/img/gallery-14-thumb.webp",
		src: "/img/gallery-14.webp"
	},
	{
		label: "Conference photo 07",
		thumb: "/img/gallery-07-thumb.webp",
		src: "/img/gallery-07.webp"
	},
	{
		label: "Aastha Patel \u2014 To Learn a Language is to Live It",
		thumb: "/img/speaker-aastha-thumb.webp",
		src: "/img/speaker-aastha.webp"
	},
	{
		label: "Giselle Ferrao, 2025 student speaker",
		thumb: "/img/winner-2025-a-thumb.webp",
		src: "/img/winner-2025-a.webp"
	},
	{
		label: "Conference photo 35",
		thumb: "/img/gallery-35-thumb.webp",
		src: "/img/gallery-35.webp"
	},
	{
		label: "Conference photo 42",
		thumb: "/img/gallery-42-thumb.webp",
		src: "/img/gallery-42.webp"
	},
	{
		label: "Conference photo 15",
		thumb: "/img/gallery-15-thumb.webp",
		src: "/img/gallery-15.webp"
	},
	{
		label: "Sid Thatham \u2014 Energy for AI and Everybody Else",
		thumb: "/img/speaker-sid-thumb.webp",
		src: "/img/speaker-sid.webp"
	},
	{
		label: "Conference photo 26",
		thumb: "/img/gallery-26-thumb.webp",
		src: "/img/gallery-26.webp"
	},
	{
		label: "Conference photo 27",
		thumb: "/img/gallery-27-thumb.webp",
		src: "/img/gallery-27.webp"
	},
	{
		label: "Conference photo 05",
		thumb: "/img/gallery-05-thumb.webp",
		src: "/img/gallery-05.webp"
	},
	{
		label: "Conference photo 02",
		thumb: "/img/gallery-02-thumb.webp",
		src: "/img/gallery-02.webp"
	},
	{
		label: "Conference photo 13",
		thumb: "/img/gallery-13-thumb.webp",
		src: "/img/gallery-13.webp"
	},
	{
		label: "Conference photo 32",
		thumb: "/img/gallery-32-thumb.webp",
		src: "/img/gallery-32.webp"
	},
	{
		label: "A salon in session",
		thumb: "/img/salon-thumb.webp",
		src: "/img/salon.webp"
	},
	{
		label: "Conference photo 37",
		thumb: "/img/gallery-37-thumb.webp",
		src: "/img/gallery-37.webp"
	},
	{
		label: "Conference photo 23",
		thumb: "/img/gallery-23-thumb.webp",
		src: "/img/gallery-23.webp"
	},
	{
		label: "Conference photo 06",
		thumb: "/img/gallery-06-thumb.webp",
		src: "/img/gallery-06.webp"
	},
	{
		label: "Conference photo 34",
		thumb: "/img/gallery-34-thumb.webp",
		src: "/img/gallery-34.webp"
	},
	{
		label: "Conference photo 04",
		thumb: "/img/gallery-04-thumb.webp",
		src: "/img/gallery-04.webp"
	},
	{
		label: "Conference photo 03",
		thumb: "/img/gallery-03-thumb.webp",
		src: "/img/gallery-03.webp"
	},
	{
		label: "Conference photo 41",
		thumb: "/img/gallery-41-thumb.webp",
		src: "/img/gallery-41.webp"
	},
	{
		label: "Conference photo 25",
		thumb: "/img/gallery-25-thumb.webp",
		src: "/img/gallery-25.webp"
	},
	{
		label: "Conference photo 09",
		thumb: "/img/gallery-09-thumb.webp",
		src: "/img/gallery-09.webp"
	},
	{
		label: "Conference photo 20",
		thumb: "/img/gallery-20-thumb.webp",
		src: "/img/gallery-20.webp"
	}
];
