#!/usr/bin/env python3
"""Turn the raw camera files in _originals into web assets.

Originals run 7-12MB each and 300MB+ in total, which is far too heavy to
commit or to serve. This resizes each one twice — a full size for the
lightbox and a thumbnail for grids — converts to WebP, bakes in EXIF
rotation (many of the originals are stored sideways) and drops all other
metadata.

Re-runnable: it rewrites static/img from scratch each time, so adding a
photo to _originals/ and running `npm run images` is the whole
workflow.
"""

from PIL import Image, ImageOps
from pathlib import Path
import json
import random
import shutil
import sys

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / '_originals'
OUT = ROOT / 'static' / 'img'
DATA = ROOT / 'src' / 'lib' / 'gallery.js'

FULL_EDGE = 1600  # longest edge for the lightbox
THUMB_EDGE = 600  # longest edge for grid tiles
QUALITY = 80

# Photos that fill a specific slot get a stable, meaningful name. Everything
# else is numbered in sorted order.
NAMED = {
    'landing_page/big.jpg': 'conference-group',
    'landing_page/small.JPG': 'audience',
    'landing_page/speakers/aastha.JPG': 'speaker-aastha',
    'landing_page/speakers/bo.jpg': 'speaker-bo',
    'landing_page/speakers/chase.JPG': 'speaker-chase',
    'landing_page/speakers/nicole.JPG': 'speaker-nicole',
    'landing_page/speakers/prady.jpg': 'speaker-prady',
    'landing_page/speakers/sid.JPG': 'speaker-sid',
    'student_speaker/DSCF7870.JPG': 'student-speaker-hero',
    'student_speaker/2026/DSC_7481.JPG': 'winner-2026',
    'student_speaker/2025/speaker_1.JPG': 'winner-2025-a',
    'student_speaker/2025/speaker_2.JPG': 'winner-2025-b',
    'DSC_7722.jpg': 'stage-group',
    'salons.jpg': 'salon',
}

SKIP = set()

EXTS = {'.jpg', '.jpeg', '.png', '.webp'}

# Captions for the photos that fill a named slot; everything else is numbered.
CAPTIONS = {
    'conference-group': 'The team on stage',
    'audience': 'The audience',
    'stage-group': 'The team after the show',
    'student-speaker-hero': 'The Loeb Playhouse stage',
    'salon': 'A salon in session',
    'winner-2026': 'Aastha Patel, 2026 student speaker',
    'winner-2025-a': 'Giselle Ferrao, 2025 student speaker',
    'winner-2025-b': 'Jyotisman Rath, 2025 student speaker',
    'speaker-bo': 'Bo Parfet — How Do You Light Your Soul on Fire?',
    'speaker-prady': 'Prady Modukuru — From Building to Founding',
    'speaker-aastha': 'Aastha Patel — To Learn a Language is to Live It',
    'speaker-chase': 'Chase Boehringer — How to do impossible things',
    'speaker-nicole': "Nicole Johnston — When Being 'Too Much' Is Actually Just Enough",
    'speaker-sid': 'Sid Thatham — Energy for AI and Everybody Else',
}


def encode(im, path, edge):
    out = ImageOps.contain(im, (edge, edge), Image.LANCZOS)
    out.save(path, 'WEBP', quality=QUALITY, method=6)
    return path.stat().st_size


def write_gallery(slugs):
    """Emit the gallery data the landing page imports.

    Generated rather than hand-maintained so adding a photo is just a re-run.
    The shuffle uses a fixed seed: the page is prerendered and paginated, so a
    random order per load would disagree with the server's HTML.
    """
    photos = [
        {
            'label': CAPTIONS.get(slug, f'Conference photo {slug.split("-")[-1]}'),
            'thumb': f'/img/{slug}-thumb.webp',
            'src': f'/img/{slug}.webp',
        }
        for slug in slugs
    ]
    random.Random(7).shuffle(photos)

    body = ',\n'.join(
        '\t{\n'
        + ',\n'.join(f'\t\t{k}: {json.dumps(v)}' for k, v in p.items())
        + '\n\t}'
        for p in photos
    )
    DATA.write_text(
        '// GENERATED by scripts/optimize-images.py — do not edit by hand.\n'
        '// Run `npm run images` after changing anything in _originals/.\n'
        '/** @type {{ label: string, thumb: string, src: string }[]} */\n'
        f'export const gallery = [\n{body}\n];\n'
    )


def main():
    if not SRC.is_dir():
        sys.exit(f'no originals at {SRC}')

    if OUT.exists():
        shutil.rmtree(OUT)
    OUT.mkdir(parents=True)

    files = sorted(
        p for p in SRC.rglob('*')
        if p.is_file() and p.suffix.lower() in EXTS
    )

    seq = 0
    total_in = total_out = 0
    rows = []

    for path in files:
        rel = path.relative_to(SRC).as_posix()
        if rel in SKIP:
            continue

        if rel in NAMED:
            slug = NAMED[rel]
        else:
            seq += 1
            slug = f'gallery-{seq:02d}'

        # Rotation lives in EXIF on 13 of these; applying it before we strip
        # metadata is what keeps them upright once the tags are gone.
        im = ImageOps.exif_transpose(Image.open(path)).convert('RGB')

        total_in += path.stat().st_size
        total_out += encode(im, OUT / f'{slug}.webp', FULL_EDGE)
        total_out += encode(im, OUT / f'{slug}-thumb.webp', THUMB_EDGE)
        rows.append((slug, rel))

    write_gallery([slug for slug, _ in rows])

    for slug, rel in rows:
        print(f'  {slug:20s} <- {rel}')
    print(f'\n{len(rows)} photos: {total_in/1048576:.0f} MB -> {total_out/1048576:.1f} MB')
    print(f'wrote {DATA.relative_to(ROOT)}')


if __name__ == '__main__':
    main()
